---
label: project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: image_gallery
  name: images
  label: images
  description: project images
- type: text
  name: basic-mode
  label: basic-mode
- type: text
  name: permalink
  label: permalink
pages:
- index.markdown
